# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AnnouncementCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, title: str=None, body: str=None, staticfile_id: int=None, course_id: int=None):  # noqa: E501
        """AnnouncementCreate - a model defined in Swagger

        :param title: The title of this AnnouncementCreate.  # noqa: E501
        :type title: str
        :param body: The body of this AnnouncementCreate.  # noqa: E501
        :type body: str
        :param staticfile_id: The staticfile_id of this AnnouncementCreate.  # noqa: E501
        :type staticfile_id: int
        :param course_id: The course_id of this AnnouncementCreate.  # noqa: E501
        :type course_id: int
        """
        self.swagger_types = {
            'title': str,
            'body': str,
            'staticfile_id': int,
            'course_id': int
        }

        self.attribute_map = {
            'title': 'title',
            'body': 'body',
            'staticfile_id': 'staticfile_id',
            'course_id': 'course_id'
        }
        self._title = title
        self._body = body
        self._staticfile_id = staticfile_id
        self._course_id = course_id

    @classmethod
    def from_dict(cls, dikt) -> 'AnnouncementCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Announcement-create of this AnnouncementCreate.  # noqa: E501
        :rtype: AnnouncementCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this AnnouncementCreate.


        :return: The title of this AnnouncementCreate.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this AnnouncementCreate.


        :param title: The title of this AnnouncementCreate.
        :type title: str
        """

        self._title = title

    @property
    def body(self) -> str:
        """Gets the body of this AnnouncementCreate.


        :return: The body of this AnnouncementCreate.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this AnnouncementCreate.


        :param body: The body of this AnnouncementCreate.
        :type body: str
        """

        self._body = body

    @property
    def staticfile_id(self) -> int:
        """Gets the staticfile_id of this AnnouncementCreate.


        :return: The staticfile_id of this AnnouncementCreate.
        :rtype: int
        """
        return self._staticfile_id

    @staticfile_id.setter
    def staticfile_id(self, staticfile_id: int):
        """Sets the staticfile_id of this AnnouncementCreate.


        :param staticfile_id: The staticfile_id of this AnnouncementCreate.
        :type staticfile_id: int
        """

        self._staticfile_id = staticfile_id

    @property
    def course_id(self) -> int:
        """Gets the course_id of this AnnouncementCreate.


        :return: The course_id of this AnnouncementCreate.
        :rtype: int
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: int):
        """Sets the course_id of this AnnouncementCreate.


        :param course_id: The course_id of this AnnouncementCreate.
        :type course_id: int
        """

        self._course_id = course_id
