# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Comment(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, body: str=None, staticfile_id: str=None, parent_post: float=None, parent_comment: float=None, created_at: str=None):  # noqa: E501
        """Comment - a model defined in Swagger

        :param id: The id of this Comment.  # noqa: E501
        :type id: int
        :param body: The body of this Comment.  # noqa: E501
        :type body: str
        :param staticfile_id: The staticfile_id of this Comment.  # noqa: E501
        :type staticfile_id: str
        :param parent_post: The parent_post of this Comment.  # noqa: E501
        :type parent_post: float
        :param parent_comment: The parent_comment of this Comment.  # noqa: E501
        :type parent_comment: float
        :param created_at: The created_at of this Comment.  # noqa: E501
        :type created_at: str
        """
        self.swagger_types = {
            'id': int,
            'body': str,
            'staticfile_id': str,
            'parent_post': float,
            'parent_comment': float,
            'created_at': str
        }

        self.attribute_map = {
            'id': 'id',
            'body': 'body',
            'staticfile_id': 'staticfile_id',
            'parent_post': 'parent_post',
            'parent_comment': 'parent_comment',
            'created_at': 'createdAt'
        }
        self._id = id
        self._body = body
        self._staticfile_id = staticfile_id
        self._parent_post = parent_post
        self._parent_comment = parent_comment
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'Comment':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Comment of this Comment.  # noqa: E501
        :rtype: Comment
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Comment.


        :return: The id of this Comment.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Comment.


        :param id: The id of this Comment.
        :type id: int
        """

        self._id = id

    @property
    def body(self) -> str:
        """Gets the body of this Comment.


        :return: The body of this Comment.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this Comment.


        :param body: The body of this Comment.
        :type body: str
        """

        self._body = body

    @property
    def staticfile_id(self) -> str:
        """Gets the staticfile_id of this Comment.


        :return: The staticfile_id of this Comment.
        :rtype: str
        """
        return self._staticfile_id

    @staticfile_id.setter
    def staticfile_id(self, staticfile_id: str):
        """Sets the staticfile_id of this Comment.


        :param staticfile_id: The staticfile_id of this Comment.
        :type staticfile_id: str
        """

        self._staticfile_id = staticfile_id

    @property
    def parent_post(self) -> float:
        """Gets the parent_post of this Comment.


        :return: The parent_post of this Comment.
        :rtype: float
        """
        return self._parent_post

    @parent_post.setter
    def parent_post(self, parent_post: float):
        """Sets the parent_post of this Comment.


        :param parent_post: The parent_post of this Comment.
        :type parent_post: float
        """

        self._parent_post = parent_post

    @property
    def parent_comment(self) -> float:
        """Gets the parent_comment of this Comment.


        :return: The parent_comment of this Comment.
        :rtype: float
        """
        return self._parent_comment

    @parent_comment.setter
    def parent_comment(self, parent_comment: float):
        """Sets the parent_comment of this Comment.


        :param parent_comment: The parent_comment of this Comment.
        :type parent_comment: float
        """

        self._parent_comment = parent_comment

    @property
    def created_at(self) -> str:
        """Gets the created_at of this Comment.


        :return: The created_at of this Comment.
        :rtype: str
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: str):
        """Sets the created_at of this Comment.


        :param created_at: The created_at of this Comment.
        :type created_at: str
        """

        self._created_at = created_at
