# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CoursesUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, course_id: float=None, user_id: float=None):  # noqa: E501
        """CoursesUser - a model defined in Swagger

        :param course_id: The course_id of this CoursesUser.  # noqa: E501
        :type course_id: float
        :param user_id: The user_id of this CoursesUser.  # noqa: E501
        :type user_id: float
        """
        self.swagger_types = {
            'course_id': float,
            'user_id': float
        }

        self.attribute_map = {
            'course_id': 'course_id',
            'user_id': 'user_id'
        }
        self._course_id = course_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'CoursesUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Courses-user of this CoursesUser.  # noqa: E501
        :rtype: CoursesUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def course_id(self) -> float:
        """Gets the course_id of this CoursesUser.


        :return: The course_id of this CoursesUser.
        :rtype: float
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: float):
        """Sets the course_id of this CoursesUser.


        :param course_id: The course_id of this CoursesUser.
        :type course_id: float
        """

        self._course_id = course_id

    @property
    def user_id(self) -> float:
        """Gets the user_id of this CoursesUser.


        :return: The user_id of this CoursesUser.
        :rtype: float
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: float):
        """Sets the user_id of this CoursesUser.


        :param user_id: The user_id of this CoursesUser.
        :type user_id: float
        """

        self._user_id = user_id
