# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CourseUser(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, course_id: float=None, user_id: float=None):  # noqa: E501
        """CourseUser - a model defined in Swagger

        :param id: The id of this CourseUser.  # noqa: E501
        :type id: int
        :param course_id: The course_id of this CourseUser.  # noqa: E501
        :type course_id: float
        :param user_id: The user_id of this CourseUser.  # noqa: E501
        :type user_id: float
        """
        self.swagger_types = {
            'id': int,
            'course_id': float,
            'user_id': float
        }

        self.attribute_map = {
            'id': 'id',
            'course_id': 'course_id',
            'user_id': 'user_id'
        }
        self._id = id
        self._course_id = course_id
        self._user_id = user_id

    @classmethod
    def from_dict(cls, dikt) -> 'CourseUser':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Course-User of this CourseUser.  # noqa: E501
        :rtype: CourseUser
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this CourseUser.


        :return: The id of this CourseUser.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this CourseUser.


        :param id: The id of this CourseUser.
        :type id: int
        """

        self._id = id

    @property
    def course_id(self) -> float:
        """Gets the course_id of this CourseUser.


        :return: The course_id of this CourseUser.
        :rtype: float
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: float):
        """Sets the course_id of this CourseUser.


        :param course_id: The course_id of this CourseUser.
        :type course_id: float
        """

        self._course_id = course_id

    @property
    def user_id(self) -> float:
        """Gets the user_id of this CourseUser.


        :return: The user_id of this CourseUser.
        :rtype: float
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id: float):
        """Sets the user_id of this CourseUser.


        :param user_id: The user_id of this CourseUser.
        :type user_id: float
        """

        self._user_id = user_id
