# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class EntriesCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, day: str=None, start_time: str=None, end_time: str=None):  # noqa: E501
        """EntriesCreate - a model defined in Swagger

        :param day: The day of this EntriesCreate.  # noqa: E501
        :type day: str
        :param start_time: The start_time of this EntriesCreate.  # noqa: E501
        :type start_time: str
        :param end_time: The end_time of this EntriesCreate.  # noqa: E501
        :type end_time: str
        """
        self.swagger_types = {
            'day': str,
            'start_time': str,
            'end_time': str
        }

        self.attribute_map = {
            'day': 'day',
            'start_time': 'start_time',
            'end_time': 'end_time'
        }
        self._day = day
        self._start_time = start_time
        self._end_time = end_time

    @classmethod
    def from_dict(cls, dikt) -> 'EntriesCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Entries-create of this EntriesCreate.  # noqa: E501
        :rtype: EntriesCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def day(self) -> str:
        """Gets the day of this EntriesCreate.


        :return: The day of this EntriesCreate.
        :rtype: str
        """
        return self._day

    @day.setter
    def day(self, day: str):
        """Sets the day of this EntriesCreate.


        :param day: The day of this EntriesCreate.
        :type day: str
        """

        self._day = day

    @property
    def start_time(self) -> str:
        """Gets the start_time of this EntriesCreate.


        :return: The start_time of this EntriesCreate.
        :rtype: str
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: str):
        """Sets the start_time of this EntriesCreate.


        :param start_time: The start_time of this EntriesCreate.
        :type start_time: str
        """

        self._start_time = start_time

    @property
    def end_time(self) -> str:
        """Gets the end_time of this EntriesCreate.


        :return: The end_time of this EntriesCreate.
        :rtype: str
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time: str):
        """Sets the end_time of this EntriesCreate.


        :param end_time: The end_time of this EntriesCreate.
        :type end_time: str
        """

        self._end_time = end_time
