# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Grades(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, grade: str=None, student_id: float=None, course_id: float=None):  # noqa: E501
        """Grades - a model defined in Swagger

        :param id: The id of this Grades.  # noqa: E501
        :type id: int
        :param grade: The grade of this Grades.  # noqa: E501
        :type grade: str
        :param student_id: The student_id of this Grades.  # noqa: E501
        :type student_id: float
        :param course_id: The course_id of this Grades.  # noqa: E501
        :type course_id: float
        """
        self.swagger_types = {
            'id': int,
            'grade': str,
            'student_id': float,
            'course_id': float
        }

        self.attribute_map = {
            'id': 'id',
            'grade': 'grade',
            'student_id': 'student_id',
            'course_id': 'course_id'
        }
        self._id = id
        self._grade = grade
        self._student_id = student_id
        self._course_id = course_id

    @classmethod
    def from_dict(cls, dikt) -> 'Grades':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Grades of this Grades.  # noqa: E501
        :rtype: Grades
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Grades.


        :return: The id of this Grades.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Grades.


        :param id: The id of this Grades.
        :type id: int
        """

        self._id = id

    @property
    def grade(self) -> str:
        """Gets the grade of this Grades.


        :return: The grade of this Grades.
        :rtype: str
        """
        return self._grade

    @grade.setter
    def grade(self, grade: str):
        """Sets the grade of this Grades.


        :param grade: The grade of this Grades.
        :type grade: str
        """

        self._grade = grade

    @property
    def student_id(self) -> float:
        """Gets the student_id of this Grades.


        :return: The student_id of this Grades.
        :rtype: float
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: float):
        """Sets the student_id of this Grades.


        :param student_id: The student_id of this Grades.
        :type student_id: float
        """

        self._student_id = student_id

    @property
    def course_id(self) -> float:
        """Gets the course_id of this Grades.


        :return: The course_id of this Grades.
        :rtype: float
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: float):
        """Sets the course_id of this Grades.


        :param course_id: The course_id of this Grades.
        :type course_id: float
        """

        self._course_id = course_id
