# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StaticFilesCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: Object=None, metadata: str=None, course_id: int=None):  # noqa: E501
        """StaticFilesCreate - a model defined in Swagger

        :param file: The file of this StaticFilesCreate.  # noqa: E501
        :type file: Object
        :param metadata: The metadata of this StaticFilesCreate.  # noqa: E501
        :type metadata: str
        :param course_id: The course_id of this StaticFilesCreate.  # noqa: E501
        :type course_id: int
        """
        self.swagger_types = {
            'file': Object,
            'metadata': str,
            'course_id': int
        }

        self.attribute_map = {
            'file': 'file',
            'metadata': 'metadata',
            'course_id': 'course_id'
        }
        self._file = file
        self._metadata = metadata
        self._course_id = course_id

    @classmethod
    def from_dict(cls, dikt) -> 'StaticFilesCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The static_files-create of this StaticFilesCreate.  # noqa: E501
        :rtype: StaticFilesCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> Object:
        """Gets the file of this StaticFilesCreate.


        :return: The file of this StaticFilesCreate.
        :rtype: Object
        """
        return self._file

    @file.setter
    def file(self, file: Object):
        """Sets the file of this StaticFilesCreate.


        :param file: The file of this StaticFilesCreate.
        :type file: Object
        """

        self._file = file

    @property
    def metadata(self) -> str:
        """Gets the metadata of this StaticFilesCreate.


        :return: The metadata of this StaticFilesCreate.
        :rtype: str
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: str):
        """Sets the metadata of this StaticFilesCreate.


        :param metadata: The metadata of this StaticFilesCreate.
        :type metadata: str
        """

        self._metadata = metadata

    @property
    def course_id(self) -> int:
        """Gets the course_id of this StaticFilesCreate.


        :return: The course_id of this StaticFilesCreate.
        :rtype: int
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id: int):
        """Sets the course_id of this StaticFilesCreate.


        :param course_id: The course_id of this StaticFilesCreate.
        :type course_id: int
        """

        self._course_id = course_id
