# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Submission(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, evaluation_id: float=None, student_id: float=None, marks: float=None, staticfile_id: float=None):  # noqa: E501
        """Submission - a model defined in Swagger

        :param id: The id of this Submission.  # noqa: E501
        :type id: int
        :param evaluation_id: The evaluation_id of this Submission.  # noqa: E501
        :type evaluation_id: float
        :param student_id: The student_id of this Submission.  # noqa: E501
        :type student_id: float
        :param marks: The marks of this Submission.  # noqa: E501
        :type marks: float
        :param staticfile_id: The staticfile_id of this Submission.  # noqa: E501
        :type staticfile_id: float
        """
        self.swagger_types = {
            'id': int,
            'evaluation_id': float,
            'student_id': float,
            'marks': float,
            'staticfile_id': float
        }

        self.attribute_map = {
            'id': 'id',
            'evaluation_id': 'evaluation_id',
            'student_id': 'student_id',
            'marks': 'marks',
            'staticfile_id': 'staticfile_id'
        }
        self._id = id
        self._evaluation_id = evaluation_id
        self._student_id = student_id
        self._marks = marks
        self._staticfile_id = staticfile_id

    @classmethod
    def from_dict(cls, dikt) -> 'Submission':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Submission of this Submission.  # noqa: E501
        :rtype: Submission
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Submission.


        :return: The id of this Submission.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Submission.


        :param id: The id of this Submission.
        :type id: int
        """

        self._id = id

    @property
    def evaluation_id(self) -> float:
        """Gets the evaluation_id of this Submission.


        :return: The evaluation_id of this Submission.
        :rtype: float
        """
        return self._evaluation_id

    @evaluation_id.setter
    def evaluation_id(self, evaluation_id: float):
        """Sets the evaluation_id of this Submission.


        :param evaluation_id: The evaluation_id of this Submission.
        :type evaluation_id: float
        """

        self._evaluation_id = evaluation_id

    @property
    def student_id(self) -> float:
        """Gets the student_id of this Submission.


        :return: The student_id of this Submission.
        :rtype: float
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: float):
        """Sets the student_id of this Submission.


        :param student_id: The student_id of this Submission.
        :type student_id: float
        """

        self._student_id = student_id

    @property
    def marks(self) -> float:
        """Gets the marks of this Submission.


        :return: The marks of this Submission.
        :rtype: float
        """
        return self._marks

    @marks.setter
    def marks(self, marks: float):
        """Sets the marks of this Submission.


        :param marks: The marks of this Submission.
        :type marks: float
        """

        self._marks = marks

    @property
    def staticfile_id(self) -> float:
        """Gets the staticfile_id of this Submission.


        :return: The staticfile_id of this Submission.
        :rtype: float
        """
        return self._staticfile_id

    @staticfile_id.setter
    def staticfile_id(self, staticfile_id: float):
        """Sets the staticfile_id of this Submission.


        :param staticfile_id: The staticfile_id of this Submission.
        :type staticfile_id: float
        """

        self._staticfile_id = staticfile_id
