# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SubmissionCreate(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, evaluation_id: float=None, student_id: float=None, staticfile_id: float=None):  # noqa: E501
        """SubmissionCreate - a model defined in Swagger

        :param evaluation_id: The evaluation_id of this SubmissionCreate.  # noqa: E501
        :type evaluation_id: float
        :param student_id: The student_id of this SubmissionCreate.  # noqa: E501
        :type student_id: float
        :param staticfile_id: The staticfile_id of this SubmissionCreate.  # noqa: E501
        :type staticfile_id: float
        """
        self.swagger_types = {
            'evaluation_id': float,
            'student_id': float,
            'staticfile_id': float
        }

        self.attribute_map = {
            'evaluation_id': 'evaluation_id',
            'student_id': 'student_id',
            'staticfile_id': 'staticfile_id'
        }
        self._evaluation_id = evaluation_id
        self._student_id = student_id
        self._staticfile_id = staticfile_id

    @classmethod
    def from_dict(cls, dikt) -> 'SubmissionCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Submission-create of this SubmissionCreate.  # noqa: E501
        :rtype: SubmissionCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def evaluation_id(self) -> float:
        """Gets the evaluation_id of this SubmissionCreate.


        :return: The evaluation_id of this SubmissionCreate.
        :rtype: float
        """
        return self._evaluation_id

    @evaluation_id.setter
    def evaluation_id(self, evaluation_id: float):
        """Sets the evaluation_id of this SubmissionCreate.


        :param evaluation_id: The evaluation_id of this SubmissionCreate.
        :type evaluation_id: float
        """

        self._evaluation_id = evaluation_id

    @property
    def student_id(self) -> float:
        """Gets the student_id of this SubmissionCreate.


        :return: The student_id of this SubmissionCreate.
        :rtype: float
        """
        return self._student_id

    @student_id.setter
    def student_id(self, student_id: float):
        """Sets the student_id of this SubmissionCreate.


        :param student_id: The student_id of this SubmissionCreate.
        :type student_id: float
        """

        self._student_id = student_id

    @property
    def staticfile_id(self) -> float:
        """Gets the staticfile_id of this SubmissionCreate.


        :return: The staticfile_id of this SubmissionCreate.
        :rtype: float
        """
        return self._staticfile_id

    @staticfile_id.setter
    def staticfile_id(self, staticfile_id: float):
        """Sets the staticfile_id of this SubmissionCreate.


        :param staticfile_id: The staticfile_id of this SubmissionCreate.
        :type staticfile_id: float
        """

        self._staticfile_id = staticfile_id
