# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserSignup(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email_id: str=None, password: str=None, insti_id: int=None, is_prof: bool=None, profile_pic: str=None):  # noqa: E501
        """UserSignup - a model defined in Swagger

        :param email_id: The email_id of this UserSignup.  # noqa: E501
        :type email_id: str
        :param password: The password of this UserSignup.  # noqa: E501
        :type password: str
        :param insti_id: The insti_id of this UserSignup.  # noqa: E501
        :type insti_id: int
        :param is_prof: The is_prof of this UserSignup.  # noqa: E501
        :type is_prof: bool
        :param profile_pic: The profile_pic of this UserSignup.  # noqa: E501
        :type profile_pic: str
        """
        self.swagger_types = {
            'email_id': str,
            'password': str,
            'insti_id': int,
            'is_prof': bool,
            'profile_pic': str
        }

        self.attribute_map = {
            'email_id': 'email_id',
            'password': 'password',
            'insti_id': 'insti_id',
            'is_prof': 'is_Prof',
            'profile_pic': 'profile_pic'
        }
        self._email_id = email_id
        self._password = password
        self._insti_id = insti_id
        self._is_prof = is_prof
        self._profile_pic = profile_pic

    @classmethod
    def from_dict(cls, dikt) -> 'UserSignup':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User-signup of this UserSignup.  # noqa: E501
        :rtype: UserSignup
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email_id(self) -> str:
        """Gets the email_id of this UserSignup.


        :return: The email_id of this UserSignup.
        :rtype: str
        """
        return self._email_id

    @email_id.setter
    def email_id(self, email_id: str):
        """Sets the email_id of this UserSignup.


        :param email_id: The email_id of this UserSignup.
        :type email_id: str
        """

        self._email_id = email_id

    @property
    def password(self) -> str:
        """Gets the password of this UserSignup.


        :return: The password of this UserSignup.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this UserSignup.


        :param password: The password of this UserSignup.
        :type password: str
        """

        self._password = password

    @property
    def insti_id(self) -> int:
        """Gets the insti_id of this UserSignup.


        :return: The insti_id of this UserSignup.
        :rtype: int
        """
        return self._insti_id

    @insti_id.setter
    def insti_id(self, insti_id: int):
        """Sets the insti_id of this UserSignup.


        :param insti_id: The insti_id of this UserSignup.
        :type insti_id: int
        """

        self._insti_id = insti_id

    @property
    def is_prof(self) -> bool:
        """Gets the is_prof of this UserSignup.


        :return: The is_prof of this UserSignup.
        :rtype: bool
        """
        return self._is_prof

    @is_prof.setter
    def is_prof(self, is_prof: bool):
        """Sets the is_prof of this UserSignup.


        :param is_prof: The is_prof of this UserSignup.
        :type is_prof: bool
        """

        self._is_prof = is_prof

    @property
    def profile_pic(self) -> str:
        """Gets the profile_pic of this UserSignup.


        :return: The profile_pic of this UserSignup.
        :rtype: str
        """
        return self._profile_pic

    @profile_pic.setter
    def profile_pic(self, profile_pic: str):
        """Sets the profile_pic of this UserSignup.


        :param profile_pic: The profile_pic of this UserSignup.
        :type profile_pic: str
        """

        self._profile_pic = profile_pic
