# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserIsAuthenticated(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, is_authenticated: bool=None):  # noqa: E501
        """UserIsAuthenticated - a model defined in Swagger

        :param is_authenticated: The is_authenticated of this UserIsAuthenticated.  # noqa: E501
        :type is_authenticated: bool
        """
        self.swagger_types = {
            'is_authenticated': bool
        }

        self.attribute_map = {
            'is_authenticated': 'is_authenticated'
        }
        self._is_authenticated = is_authenticated

    @classmethod
    def from_dict(cls, dikt) -> 'UserIsAuthenticated':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User-is_authenticated of this UserIsAuthenticated.  # noqa: E501
        :rtype: UserIsAuthenticated
        """
        return util.deserialize_model(dikt, cls)

    @property
    def is_authenticated(self) -> bool:
        """Gets the is_authenticated of this UserIsAuthenticated.


        :return: The is_authenticated of this UserIsAuthenticated.
        :rtype: bool
        """
        return self._is_authenticated

    @is_authenticated.setter
    def is_authenticated(self, is_authenticated: bool):
        """Sets the is_authenticated of this UserIsAuthenticated.


        :param is_authenticated: The is_authenticated of this UserIsAuthenticated.
        :type is_authenticated: bool
        """

        self._is_authenticated = is_authenticated
