# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserProfilePic(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, profile_pic: str=None):  # noqa: E501
        """UserProfilePic - a model defined in Swagger

        :param profile_pic: The profile_pic of this UserProfilePic.  # noqa: E501
        :type profile_pic: str
        """
        self.swagger_types = {
            'profile_pic': str
        }

        self.attribute_map = {
            'profile_pic': 'profile_pic'
        }
        self._profile_pic = profile_pic

    @classmethod
    def from_dict(cls, dikt) -> 'UserProfilePic':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User-profile_pic of this UserProfilePic.  # noqa: E501
        :rtype: UserProfilePic
        """
        return util.deserialize_model(dikt, cls)

    @property
    def profile_pic(self) -> str:
        """Gets the profile_pic of this UserProfilePic.


        :return: The profile_pic of this UserProfilePic.
        :rtype: str
        """
        return self._profile_pic

    @profile_pic.setter
    def profile_pic(self, profile_pic: str):
        """Sets the profile_pic of this UserProfilePic.


        :param profile_pic: The profile_pic of this UserProfilePic.
        :type profile_pic: str
        """

        self._profile_pic = profile_pic
