# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class UserEmail(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, email_id: str=None):  # noqa: E501
        """UserEmail - a model defined in Swagger

        :param email_id: The email_id of this UserEmail.  # noqa: E501
        :type email_id: str
        """
        self.swagger_types = {
            'email_id': str
        }

        self.attribute_map = {
            'email_id': 'email_id'
        }
        self._email_id = email_id

    @classmethod
    def from_dict(cls, dikt) -> 'UserEmail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User-email of this UserEmail.  # noqa: E501
        :rtype: UserEmail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email_id(self) -> str:
        """Gets the email_id of this UserEmail.


        :return: The email_id of this UserEmail.
        :rtype: str
        """
        return self._email_id

    @email_id.setter
    def email_id(self, email_id: str):
        """Sets the email_id of this UserEmail.


        :param email_id: The email_id of this UserEmail.
        :type email_id: str
        """

        self._email_id = email_id
