"""added communication

Revision ID: 0f8e243e7296
Revises: ba2d55cd5687
Create Date: 2023-04-06 01:06:21.898773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8e243e7296'
down_revision = 'ba2d55cd5687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement__attachments',
    sa.Column('announcement_attachment_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('announcement_attachment_id')
    )
    op.create_table('announcements',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('announcement_title', sa.String(length=100), nullable=False),
    sa.Column('announcement_content', sa.Text(), nullable=False),
    sa.Column('announcement_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_table('post__attachments',
    sa.Column('post_attachment_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('post_attachment_id')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=100), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('post_likes', sa.Integer(), nullable=True),
    sa.Column('post_canComment', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.Column('comment_likes', sa.Integer(), nullable=True),
    sa.Column('comment_parentPost', sa.Integer(), nullable=True),
    sa.Column('comment_parentComment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_parentComment'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['comment_parentPost'], ['posts.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('post__attachments')
    op.drop_table('announcements')
    op.drop_table('announcement__attachments')
    # ### end Alembic commands ###
