"""added courses

Revision ID: 296bb60ff26d
Revises: cb9d64f37c1c
Create Date: 2023-04-06 00:57:34.829390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296bb60ff26d'
down_revision = 'cb9d64f37c1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_description', sa.String(length=100), nullable=False),
    sa.Column('course_image', sa.String(length=100), nullable=True),
    sa.Column('course_semester', sa.Enum('1', '2'), nullable=False),
    sa.Column('course_year', sa.Integer(), nullable=False),
    sa.Column('course_credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('user__course',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user__course')
    op.drop_table('course')
    # ### end Alembic commands ###
