"""added static_files and grades

Revision ID: 7d5c77edd7d7
Revises: 296bb60ff26d
Create Date: 2023-04-06 00:59:34.997750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d5c77edd7d7'
down_revision = '296bb60ff26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('grade_value', sa.Enum('10', '9', '8', '7', '6', '5', '4', '3', '2', '1'), nullable=False),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_table('static__files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_data', sa.String(length=200), nullable=True),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('file_course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_course'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('static__files')
    op.drop_table('grade')
    # ### end Alembic commands ###
