"""empty message

Revision ID: abefa9487f43
Revises: e7aeeeb51f78
Create Date: 2023-04-07 14:29:55.097957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abefa9487f43'
down_revision = 'e7aeeeb51f78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_parentComment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comment_parentPost', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'post', ['comment_parentPost'], ['post_id'])
        batch_op.create_foreign_key(None, 'comment', ['comment_parentComment'], ['comment_id'])

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_canComment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('post_canComment')

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_parentPost')
        batch_op.drop_column('comment_parentComment')

    # ### end Alembic commands ###
