"""added evaluations

Revision ID: ba2d55cd5687
Revises: 7d5c77edd7d7
Create Date: 2023-04-06 01:04:31.554011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2d55cd5687'
down_revision = '7d5c77edd7d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_title', sa.String(length=100), nullable=False),
    sa.Column('evaluation_content', sa.Text(), nullable=False),
    sa.Column('evaluation_submission_allowed', sa.Boolean(), nullable=True),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.Column('evaluation_deadline', sa.DateTime(), nullable=False),
    sa.Column('evaluation_max_score', sa.Float(), nullable=True),
    sa.Column('evaluation_weightage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('submissions',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('submission_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
