"""empty message

Revision ID: e7aeeeb51f78
Revises: 
Create Date: 2023-04-06 23:24:55.368737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7aeeeb51f78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('entry_day', sa.Enum('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'), nullable=False),
    sa.Column('entry_start_time', sa.Time(), nullable=False),
    sa.Column('entry_end_time', sa.Time(), nullable=False),
    sa.Column('entry_insti_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('institute',
    sa.Column('insti_id', sa.Integer(), nullable=False),
    sa.Column('insti_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('insti_id')
    )
    op.create_table('slot',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('slot_name', sa.String(length=100), nullable=False),
    sa.Column('insti_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insti_id'], ['institute.insti_id'], ),
    sa.PrimaryKeyConstraint('slot_id')
    )
    op.create_table('user',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('profile_pic', sa.String(length=100), nullable=True),
    sa.Column('insti_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['insti_id'], ['institute.insti_id'], ),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('course_description', sa.String(length=100), nullable=False),
    sa.Column('course_image', sa.String(length=100), nullable=True),
    sa.Column('course_semester', sa.Enum('1', '2'), nullable=False),
    sa.Column('course_year', sa.Integer(), nullable=False),
    sa.Column('course_credits', sa.Integer(), nullable=False),
    sa.Column('course_insti_id', sa.Integer(), nullable=False),
    sa.Column('course_slot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_insti_id'], ['institute.insti_id'], ),
    sa.ForeignKeyConstraint(['course_slot_id'], ['slot.slot_id'], ),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('slot_entry',
    sa.Column('slot_entry_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('entry', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry'], ['entry.entry_id'], ),
    sa.ForeignKeyConstraint(['slot'], ['slot.slot_id'], ),
    sa.PrimaryKeyConstraint('slot_entry_id')
    )
    op.create_table('announcement',
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('announcement_content', sa.Text(), nullable=False),
    sa.Column('announcement_author', sa.String(length=100), nullable=True),
    sa.Column('announcement_course', sa.Integer(), nullable=True),
    sa.Column('announcement_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_author'], ['user.email'], ),
    sa.ForeignKeyConstraint(['announcement_course'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.create_table('grade',
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('grade_course', sa.Integer(), nullable=True),
    sa.Column('grade_user', sa.String(length=100), nullable=True),
    sa.Column('grade_value', sa.Enum('10', '9', '8', '7', '6', '5', '4', '3', '2', '1'), nullable=False),
    sa.ForeignKeyConstraint(['grade_course'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['grade_user'], ['user.email'], ),
    sa.PrimaryKeyConstraint('grade_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=100), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('post_author', sa.String(length=100), nullable=True),
    sa.Column('post_course', sa.Integer(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=False),
    sa.Column('post_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_author'], ['user.email'], ),
    sa.ForeignKeyConstraint(['post_course'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('static_file',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('file_course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_course'], ['course.course_id'], ),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('user_course',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.email'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('announcement_attachment',
    sa.Column('announcement_attachment_id', sa.Integer(), nullable=False),
    sa.Column('announcement_attachment_file', sa.Integer(), nullable=True),
    sa.Column('announcement_attachment_announcement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_attachment_announcement'], ['announcement.announcement_id'], ),
    sa.ForeignKeyConstraint(['announcement_attachment_file'], ['static_file.file_id'], ),
    sa.PrimaryKeyConstraint('announcement_attachment_id')
    )
    op.create_table('comment',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_author', sa.String(length=100), nullable=True),
    sa.Column('comment_post', sa.Integer(), nullable=True),
    sa.Column('comment_date', sa.DateTime(), nullable=False),
    sa.Column('comment_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_author'], ['user.email'], ),
    sa.ForeignKeyConstraint(['comment_post'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('evaluation',
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_title', sa.String(length=100), nullable=False),
    sa.Column('evaluation_content', sa.Text(), nullable=False),
    sa.Column('evaluation_course', sa.Integer(), nullable=True),
    sa.Column('evaluation_file', sa.Integer(), nullable=True),
    sa.Column('evaluation_submission_allowed', sa.Boolean(), nullable=True),
    sa.Column('evaluation_date', sa.DateTime(), nullable=False),
    sa.Column('evaluation_deadline', sa.DateTime(), nullable=False),
    sa.Column('evaluation_obtained_score', sa.Float(), nullable=True),
    sa.Column('evaluation_max_score', sa.Float(), nullable=True),
    sa.Column('evaluation_weightage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_course'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['evaluation_file'], ['static_file.file_id'], ),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_table('post_attachment',
    sa.Column('post_attachment_id', sa.Integer(), nullable=False),
    sa.Column('post_attachment_file', sa.Integer(), nullable=True),
    sa.Column('post_attachment_post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_attachment_file'], ['static_file.file_id'], ),
    sa.ForeignKeyConstraint(['post_attachment_post'], ['post.post_id'], ),
    sa.PrimaryKeyConstraint('post_attachment_id')
    )
    op.create_table('submission',
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('submission_file', sa.Integer(), nullable=True),
    sa.Column('submission_evaluation', sa.Integer(), nullable=True),
    sa.Column('submission_author', sa.String(length=100), nullable=True),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('submission_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_author'], ['user.email'], ),
    sa.ForeignKeyConstraint(['submission_evaluation'], ['evaluation.evaluation_id'], ),
    sa.ForeignKeyConstraint(['submission_file'], ['static_file.file_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission')
    op.drop_table('post_attachment')
    op.drop_table('evaluation')
    op.drop_table('comment')
    op.drop_table('announcement_attachment')
    op.drop_table('user_course')
    op.drop_table('static_file')
    op.drop_table('post')
    op.drop_table('grade')
    op.drop_table('announcement')
    op.drop_table('slot_entry')
    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('slot')
    op.drop_table('institute')
    op.drop_table('entry')
    # ### end Alembic commands ###
